# Generated by Django 4.0.4 on 2022-05-31 15:17

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('F', 'Food'), ('C', 'Clothes'), ('T', 'Technology'), ('O', 'Other')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pubblication_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
