# Generated by Django 4.0.4 on 2022-05-23 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('can_vote', 'Can Vote Polls'),)},
        ),
    ]
