# Generated by Django 4.0.5 on 2022-06-13 15:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEMPERATURA', 'TEMPERATURA'), ('PM10', 'PM10')], default='TEMPERATURA', max_length=11)),
                ('address', models.CharField(max_length=50)),
                ('cap', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEMPERATURA', 'TEMPERATURA'), ('PM10', 'PM10')], default='TEMPERATURA', max_length=11)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.IntegerField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_monitor.sensor')),
            ],
        ),
    ]
